/**
 * The LINK STORE email design system.
 *
 * Every message the platform sends wears the same shell: the LINK ICON mark,
 * one strong hierarchy, the accent trio at the edges, a single clear action and
 * a professional footer. Nothing here is a generic template — the shell is the
 * platform's identity translated into the one medium that cannot run its
 * design system (email clients render tables and inline styles, nothing else).
 *
 * The mark is the chain-link glyph the whole platform is named for; because
 * email clients do not render SVG, it ships as a PNG at
 * `/public/brand/link-mark.png` (generated by
 * `scripts/generate-brand-assets.mjs`) and is referenced by absolute URL, with
 * a text wordmark beside it so the message still reads as LINK STORE when a
 * client blocks images.
 *
 * Everything is table-based and inline-styled on purpose: that is the only
 * layout that survives Outlook, Gmail and Apple Mail with the same result.
 */

import { platformConfig } from "../env";

/** The accent trio, as the hex values the platform's OKLab tokens resolve to. */
const BRAND = {
  iris: "#bcaef9",
  irisDeep: "#554695",
  irisSoft: "#e0d8fd",
  milk: "#f7e6c3",
  ink: "#1f1d2d",
  snow: "#fafafd",
  background: "#f4f4f8",
  text: "#3f3d52",
  muted: "#6e6b82",
  hairline: "#e7e5f0",
} as const;

const FONT =
  "-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif";

/** The LINK ICON mark, served from the platform itself. */
function logo(): string {
  return `${platformConfig.appUrl}/brand/link-mark.png`;
}

/** A primary action. One per message — a call to action is a singular thing. */
export function emailButton(label: string, url: string): string {
  return `<table role="presentation" cellpadding="0" cellspacing="0" style="margin:24px 0 4px">
    <tr>
      <td style="border-radius:12px;background:${BRAND.ink}">
        <a href="${url}" style="display:inline-block;padding:14px 26px;font-size:15px;font-weight:600;color:${BRAND.snow};text-decoration:none;border-radius:12px;font-family:${FONT}">${label}</a>
      </td>
    </tr>
  </table>`;
}

/** A secondary action — quieter, for the alternative path. */
export function emailLink(label: string, url: string): string {
  return `<p style="margin:18px 0 0;font-size:13.5px;line-height:1.6;color:${BRAND.muted};font-family:${FONT}">
    Or copy this link into your browser:<br>
    <a href="${url}" style="color:${BRAND.irisDeep};word-break:break-all">${url}</a>
  </p>`;
}

/**
 * The highlighted code block — a one-time code, a ticket code, an order
 * number. Mono-spaced, generous, and never an image: the code must survive
 * being read as plain text or copied out of a blocked client.
 */
export function emailCode(code: string, { spaced = false }: { spaced?: boolean } = {}): string {
  const shown = spaced ? code.split("").join(" ") : code;
  return `<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="margin:20px 0;background:${BRAND.irisSoft};border-radius:14px">
    <tr>
      <td style="padding:20px 16px;text-align:center;font-family:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;font-size:26px;font-weight:700;letter-spacing:.22em;color:${BRAND.ink}">
        ${shown}
      </td>
    </tr>
  </table>`;
}

/** Label/value rows — an invoice total, an event's date and venue. */
export function emailRows(rows: Array<{ label: string; value: string; strong?: boolean }>): string {
  return `<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="margin:18px 0;border-collapse:collapse">
    ${rows
      .map(
        (row) => `<tr>
      <td style="padding:8px 0;font-size:14px;color:${BRAND.muted};font-family:${FONT}">${row.label}</td>
      <td style="padding:8px 0;text-align:right;font-size:${row.strong ? "16px" : "14px"};font-weight:${row.strong ? "700" : "600"};color:${BRAND.ink};font-family:${FONT}">${row.value}</td>
    </tr>`,
      )
      .join("")}
  </table>`;
}

/** Quiet explanatory copy. */
export function emailParagraph(text: string): string {
  return `<p style="margin:0 0 16px;font-size:14.5px;line-height:1.7;color:${BRAND.text};font-family:${FONT}">${text}</p>`;
}

/** A bordered panel for content that stands alone — a ticket, a receipt line. */
export function emailPanel(inner: string): string {
  return `<table role="presentation" cellpadding="0" cellspacing="0" width="100%" style="margin:18px 0;border:1px solid ${BRAND.hairline};border-radius:16px;background:${BRAND.snow}">
    <tr>
      <td style="padding:20px">${inner}</td>
    </tr>
  </table>`;
}

/**
 * The shell every message lives in.
 *
 * Three layers: the ground (a quiet neutral field), the card (one solid white
 * surface with the mark, the message and its action), and the footer (who sent
 * this and why). The wordmark always sits beside the mark, so the message is
 * identifiable even where images are blocked.
 */
export function brandShell({
  title,
  preheader,
  body,
}: {
  /** The message's one-line headline. */
  title: string;
  /** The preview text shown beside the subject in the inbox. */
  preheader: string;
  /** The message body — built with the helpers above. */
  body: string;
}): string {
  return `<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="color-scheme" content="light" />
    <title>${title}</title>
  </head>
  <body style="margin:0;padding:0;background:${BRAND.background};font-family:${FONT};color:${BRAND.text}">
    <div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent">${preheader}</div>
    <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background:${BRAND.background}">
      <tr>
        <td style="padding:32px 16px">
          <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;margin:0 auto">
            <tr>
              <td style="padding:0 0 18px">
                <!-- The LINK ICON, with the wordmark beside it. -->
                <table role="presentation" cellpadding="0" cellspacing="0">
                  <tr>
                    <td style="padding-right:10px;vertical-align:middle">
                      <img alt="LINK STORE" height="40" src="${logo()}" style="display:block;border-radius:11px" width="40" />
                    </td>
                    <td style="vertical-align:middle;font-size:16px;font-weight:700;letter-spacing:-0.01em;color:${BRAND.ink};font-family:${FONT}">
                      LINK <span style="color:${BRAND.irisDeep}">STORE</span>
                    </td>
                  </tr>
                </table>
              </td>
            </tr>
            <tr>
              <td style="background:${BRAND.snow};border-radius:20px;padding:32px 28px;box-shadow:0 1px 2px rgba(31,29,45,0.05),0 12px 32px rgba(31,29,45,0.07)">
                <!-- The accent trio, at the edge — one hairline of identity. -->
                <table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="margin:0 0 20px">
                  <tr>
                    <td width="33%" style="height:4px;border-radius:999px;background:${BRAND.iris}"></td>
                    <td width="34%" style="height:4px;border-radius:999px;background:${BRAND.irisDeep}"></td>
                    <td width="33%" style="height:4px;border-radius:999px;background:${BRAND.milk}"></td>
                  </tr>
                </table>
                <h1 style="margin:0 0 18px;font-size:22px;line-height:1.3;font-weight:700;letter-spacing:-0.01em;color:${BRAND.ink};font-family:${FONT}">${title}</h1>
                ${body}
              </td>
            </tr>
            <tr>
              <td style="padding:22px 4px 0">
                <p style="margin:0 0 6px;font-size:12px;line-height:1.7;color:${BRAND.muted};font-family:${FONT}">
                  Sent by <strong style="color:${BRAND.ink}">LINK STORE</strong> — one link, everything you sell.
                </p>
                <p style="margin:0 0 6px;font-size:12px;line-height:1.7;color:${BRAND.muted};font-family:${FONT}">
                  <a href="${platformConfig.appUrl}" style="color:${BRAND.irisDeep};text-decoration:none">Visit LINK STORE</a>
                  &nbsp;·&nbsp;
                  <a href="${platformConfig.appUrl}/orders" style="color:${BRAND.irisDeep};text-decoration:none">Your orders</a>
                  &nbsp;·&nbsp;
                  <a href="${platformConfig.appUrl}/settings" style="color:${BRAND.irisDeep};text-decoration:none">Account settings</a>
                </p>
                <p style="margin:0;font-size:12px;line-height:1.7;color:${BRAND.muted};font-family:${FONT}">
                  Questions? Just reply to this email and a human will read it.
                </p>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    </table>
  </body>
</html>`;
}

/** The plain-text counterpart every message must carry. */
export function brandText(lines: string[]): string {
  return [...lines, "", "— LINK STORE · one link, everything you sell"].join("\n");
}
