-- Product categories are reference data, never fabricated marketplace content.
INSERT OR IGNORE INTO categories (id, store_id, parent_id, name, slug, kind, icon, position) VALUES
 ('cat_platform_fashion', NULL, NULL, 'Fashion', 'fashion', 'product', 'fashion', 1),
 ('cat_platform_clothing', NULL, 'cat_platform_fashion', 'Clothing', 'clothing', 'product', 'fashion', 2),
 ('cat_platform_shoes', NULL, 'cat_platform_fashion', 'Shoes', 'shoes', 'product', 'fashion', 3),
 ('cat_platform_accessories', NULL, NULL, 'Accessories', 'accessories', 'product', 'tag', 4),
 ('cat_platform_electronics', NULL, NULL, 'Electronics', 'electronics', 'product', 'electronics', 5),
 ('cat_platform_beauty', NULL, NULL, 'Beauty', 'beauty', 'product', 'beauty', 6),
 ('cat_platform_home', NULL, NULL, 'Home', 'home', 'product', 'home', 7),
 ('cat_platform_sports', NULL, NULL, 'Sports', 'sports', 'product', 'tag', 8),
 ('cat_platform_collectibles', NULL, NULL, 'Collectibles', 'collectibles', 'product', 'tag', 9),
 ('cat_platform_digital', NULL, NULL, 'Digital', 'digital', 'product', 'digital', 10),
 ('cat_platform_books', NULL, NULL, 'Books & stationery', 'books', 'product', 'tag', 11),
 ('cat_platform_toys', NULL, NULL, 'Toys & games', 'toys', 'product', 'tag', 12),
 ('cat_platform_baby', NULL, NULL, 'Baby & kids', 'baby', 'product', 'tag', 13),
 ('cat_platform_pets', NULL, NULL, 'Pet supplies', 'pets', 'product', 'tag', 14),
 ('cat_platform_health', NULL, NULL, 'Health & wellness', 'health', 'product', 'tag', 15),
 ('cat_platform_grocery', NULL, NULL, 'Grocery & pantry', 'grocery', 'product', 'tag', 16),
 ('cat_platform_garden', NULL, NULL, 'Garden & outdoors', 'garden', 'product', 'tag', 17),
 ('cat_platform_tools', NULL, NULL, 'Tools & hardware', 'tools', 'product', 'tag', 18),
 ('cat_platform_automotive', NULL, NULL, 'Automotive accessories', 'automotive', 'product', 'tag', 19),
 ('cat_platform_arts', NULL, NULL, 'Arts & crafts', 'arts', 'product', 'tag', 20),
 ('cat_platform_office', NULL, NULL, 'Office supplies', 'office', 'product', 'tag', 21),
 ('cat_platform_music', NULL, NULL, 'Musical instruments', 'music', 'product', 'tag', 22);
